import { useRef, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { FileSpreadsheet, Loader2, Upload } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const placeholderImage = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='900' height='1125' viewBox='0 0 900 1125'%3E%3Crect width='900' height='1125' fill='%23f4efe6'/%3E%3Ccircle cx='450' cy='530' r='210' fill='none' stroke='%23a77a43' stroke-width='26'/%3E%3Ccircle cx='450' cy='530' r='160' fill='%23fffaf0' stroke='%23d0b27c' stroke-width='8'/%3E%3Cpath d='M450 410v120l86 58' stroke='%232b2720' stroke-width='14' stroke-linecap='round' fill='none'/%3E%3Ctext x='450' y='980' text-anchor='middle' font-family='Georgia,serif' font-size='58' fill='%232b2720'%3ETIMERA%3C/text%3E%3C/svg%3E";
type CsvRow = Record<string, string>;
const aliases: Record<string, string[]> = {
  name: ["name", "productname", "title"], slug: ["slug", "handle"], brand: ["brand", "vendor"], collection: ["collection", "series"], category: ["category", "type"], price: ["price", "regularprice"], sale_price: ["saleprice", "offerprice"], compare_at: ["compareat", "oldprice", "mrp"], image_url: ["image", "imageurl", "mainimage"], gallery: ["gallery", "images"], movement: ["movement"], case_material: ["casematerial", "case"], strap: ["strap", "band"], water_resistance: ["waterresistance"], description: ["description", "body"], features: ["features", "specs"], colors: ["colors", "colours", "color"], sizes: ["sizes", "size"], stock: ["stock", "inventory", "qty"], badge: ["badge", "tag"], active: ["active", "published", "status"], featured: ["featured"], sort_order: ["sortorder", "position"], seo_title: ["seotitle", "metatitle"], seo_description: ["seodescription", "metadescription"], seo_keywords: ["seokeywords", "keywords"],
};
const norm = (v: string) => v.toLowerCase().replace(/[^a-z0-9]/g, "");
const slugify = (v: string) => v.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 90);
const list = (v: string) => v.split(/[\n;|]+/).map((x) => x.trim()).filter(Boolean);
const num = (v: string, fallback: number | null = null) => { const n = Number(v.replace(/[^0-9.-]/g, "")); return Number.isFinite(n) ? n : fallback; };
const bool = (v: string, fallback = false) => v.trim() ? ["1", "yes", "true", "live", "active", "published"].includes(v.trim().toLowerCase()) : fallback;
function read(row: CsvRow, field: keyof typeof aliases) { for (const key of aliases[field]) if (row[key]?.trim()) return row[key].trim(); return ""; }
function parseCsv(text: string) {
  const rows: string[][] = []; let row: string[] = []; let cell = ""; let q = false;
  for (let i = 0; i < text.length; i += 1) { const c = text[i]; const n = text[i + 1]; if (c === '"') { if (q && n === '"') { cell += '"'; i += 1; } else q = !q; } else if (c === "," && !q) { row.push(cell.trim()); cell = ""; } else if ((c === "\n" || c === "\r") && !q) { if (c === "\r" && n === "\n") i += 1; row.push(cell.trim()); if (row.some(Boolean)) rows.push(row); row = []; cell = ""; } else cell += c; }
  row.push(cell.trim()); if (row.some(Boolean)) rows.push(row); return rows;
}
function build(row: CsvRow, i: number) {
  const name = read(row, "name"); if (!name) return null;
  const image = read(row, "image_url") || placeholderImage; const slug = slugify(read(row, "slug") || name); if (!slug) return null;
  return { name, slug, brand: read(row, "brand") || "Timera", collection: read(row, "collection") || "Signature", category: read(row, "category") || null, price: num(read(row, "price"), 0) ?? 0, sale_price: num(read(row, "sale_price")), compare_at: num(read(row, "compare_at")), image_url: image, gallery: list(read(row, "gallery")).length ? list(read(row, "gallery")) : [image], movement: read(row, "movement") || "Quartz", case_material: read(row, "case_material") || "Stainless Steel", strap: read(row, "strap") || "Premium Strap", water_resistance: read(row, "water_resistance") || "30m", rating: 4.8, reviews: 0, badge: read(row, "badge") || null, stock: num(read(row, "stock"), 10) ?? 10, description: read(row, "description") || `${name} by Timera.`, features: list(read(row, "features")), colors: list(read(row, "colors")).length ? list(read(row, "colors")) : ["Black #111111", "Silver #c0c5cd"], sizes: list(read(row, "sizes")).length ? list(read(row, "sizes")) : ["Standard"], featured: bool(read(row, "featured")), active: bool(read(row, "active"), true), sort_order: num(read(row, "sort_order"), i + 1) ?? i + 1, deal_id: null, seo_title: read(row, "seo_title") || null, seo_description: read(row, "seo_description") || null, seo_keywords: read(row, "seo_keywords") || null };
}
export function ProductCsvImport() {
  const inputRef = useRef<HTMLInputElement>(null); const [busy, setBusy] = useState(false); const qc = useQueryClient();
  const importFile = async (files: FileList | null) => { const file = files?.[0]; if (!file) return; setBusy(true); try { const table = parseCsv(await file.text()); const headers = table[0]?.map(norm) ?? []; const products = table.slice(1).map((cells, i) => { const row: CsvRow = {}; headers.forEach((h, idx) => { row[h] = cells[idx] ?? ""; }); return build(row, i); }).filter((x): x is NonNullable<typeof x> => Boolean(x)); if (!products.length) throw new Error("No valid products found in this CSV."); for (let s = 0; s < products.length; s += 100) { const { error } = await (supabase.from("products") as any).upsert(products.slice(s, s + 100), { onConflict: "slug" }); if (error) throw error; } await qc.invalidateQueries({ queryKey: ["admin", "products"] }); await qc.invalidateQueries({ queryKey: ["products"] }); toast.success(`${products.length} products imported — live on storefront.`); } catch (error: any) { toast.error(error?.message ?? "CSV import failed."); } finally { setBusy(false); if (inputRef.current) inputRef.current.value = ""; } };
  return <div className="rounded-xl border border-border bg-card p-4 sm:p-5"><div className="grid gap-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div><p className="flex items-center gap-2 text-[11px] uppercase tracking-widest text-primary"><FileSpreadsheet className="h-4 w-4" /> CSV product import</p><p className="mt-1 text-sm text-muted-foreground">Upload a CSV; matching slugs update, new slugs create products instantly.</p></div><div className="flex flex-col gap-2 sm:flex-row"><Input ref={inputRef} type="file" accept=".csv,text/csv" className="h-11 sm:w-64" onChange={(e) => importFile(e.target.files)} /><Button type="button" disabled={busy} onClick={() => inputRef.current?.click()} className="h-11 shrink-0">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Upload className="h-4 w-4" />}<span className="ml-2">Import</span></Button></div></div></div>;
}